// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZQyy5xnB2FAAJQbkilZRXFqy7A2F3JDQ',
    appId: '1:1066090457718:web:86bd4bc1aa306840748d57',
    messagingSenderId: '1066090457718',
    projectId: 'target-5ed6d',
    authDomain: 'target-5ed6d.firebaseapp.com',
    storageBucket: 'target-5ed6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA84sZvtbIoOzhhQjwyXytVH17C_FVXLic',
    appId: '1:1066090457718:android:5e57f2e21a727992748d57',
    messagingSenderId: '1066090457718',
    projectId: 'target-5ed6d',
    storageBucket: 'target-5ed6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Fl6K3HXU7SLgC4yUjFM88HDZHmlYG6U',
    appId: '1:1066090457718:ios:1724c462f768dccb748d57',
    messagingSenderId: '1066090457718',
    projectId: 'target-5ed6d',
    storageBucket: 'target-5ed6d.appspot.com',
    iosBundleId: 'com.example.testeTarget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Fl6K3HXU7SLgC4yUjFM88HDZHmlYG6U',
    appId: '1:1066090457718:ios:55b8b2490f0c8cb3748d57',
    messagingSenderId: '1066090457718',
    projectId: 'target-5ed6d',
    storageBucket: 'target-5ed6d.appspot.com',
    iosBundleId: 'com.example.testeTarget.RunnerTests',
  );
}
